name: xxh3
description: An extremely quick and dirty XXH3 implementation in Dart.
version: 0.0.1
repository: https://github.com/SamJakob/xxh3

environment:
  sdk: '>=2.16.2 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
