name: xxh3
description: A Dart implementation (port) of the XXH3 hashing algorithm from xxHash.
version: 0.0.2+1
repository: https://github.com/SamJakob/xxh3

environment:
  sdk: '>=2.16.2 <3.0.0'

dev_dependencies:
  lints: ^1.0.1
